"""Python-facing Manyfold API backed by a Rust in-memory runtime."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS_BY_MODULE = {
    "manyfold._manyfold_rust": (
        "ClockDomainRef",
        "ClosedEnvelope",
        "ControlLoop",
        "CreditSnapshot",
        "Layer",
        "Mailbox",
        "MailboxDescriptor",
        "NamespaceRef",
        "OpenedEnvelope",
        "PayloadRef",
        "Plane",
        "PortDescriptor",
        "ProducerKind",
        "ProducerRef",
        "ReadablePort",
        "RouteRef",
        "RuntimeRef",
        "ScheduleGuard",
        "SchemaRef",
        "TaintDomain",
        "TaintMark",
        "Variant",
        "WritablePort",
        "WriteBinding",
        "bridge_version",
        "parse_sql_statement",
    ),
    "manyfold.components": (
        "Consensus",
        "ConsensusRoutes",
        "EventLog",
        "EventLogRecord",
        "EventLogRoutes",
        "FileStore",
        "Keyspace",
        "Memory",
        "MemoryRecord",
        "SnapshotStore",
        "SnapshotStoreRoutes",
        "StoreEntry",
    ),
    "manyfold.embedded": (
        "EmbeddedBulkSensor",
        "EmbeddedDeviceProfile",
        "EmbeddedRuntimeRules",
        "EmbeddedScalarSensor",
        "FirmwareAgentProfile",
    ),
    "manyfold.graph": (
        "CallbackNode",
        "CallbackObservable",
        "CallbackSubscription",
        "Capacitor",
        "CoalesceLatestNode",
        "CombineLatestNode",
        "CompositeSubscription",
        "ConstantNode",
        "ControlLoops",
        "CorrelationTracingStore",
        "DiagramNode",
        "EmptyNode",
        "EventStream",
        "FilterNode",
        "FlowPolicy",
        "FlowSnapshot",
        "Graph",
        "GraphConnection",
        "GraphContext",
        "GraphManifest",
        "Interval",
        "IntervalNode",
        "JoinInput",
        "LazyPayloadSource",
        "LifecycleBinding",
        "LineageRecord",
        "LoggingNode",
        "MailboxSnapshot",
        "MainThreadNode",
        "ManifestDebugRoute",
        "ManifestDiagramNode",
        "ManifestEdge",
        "ManifestLink",
        "ManifestMeshPrimitive",
        "ManifestQueryService",
        "ManifestRoute",
        "ManifestWriteBinding",
        "MapNode",
        "MergeNode",
        "NativeCorrelationTracingStore",
        "NodeThreadPlacement",
        "NoopCorrelationTracingStore",
        "NoopSubscription",
        "PayloadDemandSnapshot",
        "ProcessEndpoint",
        "ProcessRpcAuditEntry",
        "ProcessRpcFailure",
        "ProcessRpcRequest",
        "ProcessRpcResponse",
        "ProcessRpcRoutes",
        "ProcessRpcTransport",
        "Resistor",
        "RetentionSnapshot",
        "RetryPolicy",
        "RouteAuditSnapshot",
        "RoutePipeline",
        "RouteRetentionPolicy",
        "ScheduledWriteSnapshot",
        "ShadowSnapshot",
        "StreamNode",
        "TaintRepair",
        "Timer",
        "Watchdog",
        "WatermarkSnapshot",
        "WriteBindings",
        "instrument_stream",
    ),
    "manyfold.lego_catalog": (
        "Lego",
        "all_legos",
        "dependencies_of",
        "dependency_closure_of",
        "dependents_of",
        "get_lego",
        "legos_by_layer",
        "legos_by_role",
    ),
    "manyfold.primitives": (
        "Contract",
        "OwnerName",
        "ReadThenWriteNextEpochStep",
        "RouteIdentity",
        "RouteNamespace",
        "RouteScope",
        "Schema",
        "Sink",
        "Source",
        "StreamFamily",
        "StreamName",
        "TypedEnvelope",
        "TypedRoute",
        "logical_routes",
        "route",
        "sink",
        "source",
    ),
    "manyfold.stream_threads": (
        "drain_frame_thread_queue",
        "shutdown",
    ),
    "manyfold.reference_examples": (
        "REFERENCE_EXAMPLE_SUITE",
        "ReferenceExample",
        "implemented_reference_examples",
        "reference_example_suite",
    ),
    "manyfold.sensor_io": (
        "BackoffPolicy",
        "BoundedRingBuffer",
        "ChangeFilter",
        "Clock",
        "DelimitedMessageBuffer",
        "DetectionNode",
        "DetectionNodeHandle",
        "DoubleBuffer",
        "DuplexSensorPeripheral",
        "FrameAssembler",
        "GraphAccessNode",
        "HealthStatus",
        "JsonEventDecoder",
        "LocalDurableSpool",
        "LocalSensorSource",
        "ManagedGraphNode",
        "ManagedGraphNodeHandle",
        "ManagedRunLoop",
        "ManagedRunLoopHandle",
        "ManualClock",
        "PeripheralAdapter",
        "PeripheralAdapterHandle",
        "RateMatchedSensor",
        "ReactiveSensorHandle",
        "ReactiveSensorSource",
        "RetryLoop",
        "SensorDebugEnvelope",
        "SensorDebugStage",
        "SensorDebugTap",
        "SensorEvent",
        "SensorFrame",
        "SensorHealthHandle",
        "SensorHealthWatchdog",
        "SensorIdentity",
        "SensorLocation",
        "SensorSample",
        "SensorSourceHandle",
        "SensorTag",
        "SequenceCounter",
        "StopToken",
        "SystemClock",
        "ThresholdFilter",
        "health_status_schema",
        "sensor_event_schema",
        "sensor_sample_schema",
        "xor_checksum",
    ),
    "manyfold.stats": ("Average",),
}

_ALIASED_EXPORTS = {
    "SensorBackoffPolicy": ("manyfold.sensor_io", "BackoffPolicy"),
    "SensorRetryPolicy": ("manyfold.sensor_io", "RetryPolicy"),
}
_EXPORT_MODULE_BY_NAME = {
    name: module_name
    for module_name, names in _EXPORTS_BY_MODULE.items()
    for name in names
}


def __getattr__(name: str) -> Any:
    if name in _ALIASED_EXPORTS:
        module_name, attribute_name = _ALIASED_EXPORTS[name]
    else:
        module_name = _EXPORT_MODULE_BY_NAME.get(name)
        if module_name is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        attribute_name = name
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted((*globals(), *__all__))


__all__ = (
    "Average",
    "BackoffPolicy",
    "BoundedRingBuffer",
    "CallbackNode",
    "CallbackObservable",
    "CallbackSubscription",
    "Capacitor",
    "ChangeFilter",
    "Clock",
    "ClockDomainRef",
    "ClosedEnvelope",
    "CoalesceLatestNode",
    "CombineLatestNode",
    "CompositeSubscription",
    "Consensus",
    "ConsensusRoutes",
    "ConstantNode",
    "Contract",
    "ControlLoop",
    "ControlLoops",
    "CorrelationTracingStore",
    "CreditSnapshot",
    "DelimitedMessageBuffer",
    "DetectionNode",
    "DetectionNodeHandle",
    "DiagramNode",
    "DoubleBuffer",
    "DuplexSensorPeripheral",
    "EmbeddedBulkSensor",
    "EmbeddedDeviceProfile",
    "EmbeddedRuntimeRules",
    "EmbeddedScalarSensor",
    "EmptyNode",
    "EventLog",
    "EventLogRecord",
    "EventLogRoutes",
    "EventStream",
    "FileStore",
    "FilterNode",
    "FirmwareAgentProfile",
    "FlowPolicy",
    "FlowSnapshot",
    "FrameAssembler",
    "Graph",
    "GraphAccessNode",
    "GraphConnection",
    "GraphContext",
    "GraphManifest",
    "HealthStatus",
    "Interval",
    "IntervalNode",
    "JoinInput",
    "JsonEventDecoder",
    "Keyspace",
    "Layer",
    "LazyPayloadSource",
    "Lego",
    "LifecycleBinding",
    "LineageRecord",
    "LocalDurableSpool",
    "LocalSensorSource",
    "LoggingNode",
    "Mailbox",
    "MailboxDescriptor",
    "MailboxSnapshot",
    "MainThreadNode",
    "ManagedGraphNode",
    "ManagedGraphNodeHandle",
    "ManagedRunLoop",
    "ManagedRunLoopHandle",
    "ManifestDebugRoute",
    "ManifestDiagramNode",
    "ManifestEdge",
    "ManifestLink",
    "ManifestMeshPrimitive",
    "ManifestQueryService",
    "ManifestRoute",
    "ManifestWriteBinding",
    "ManualClock",
    "MapNode",
    "Memory",
    "MemoryRecord",
    "MergeNode",
    "NamespaceRef",
    "NativeCorrelationTracingStore",
    "NodeThreadPlacement",
    "NoopCorrelationTracingStore",
    "NoopSubscription",
    "OpenedEnvelope",
    "OwnerName",
    "PayloadDemandSnapshot",
    "PayloadRef",
    "PeripheralAdapter",
    "PeripheralAdapterHandle",
    "Plane",
    "PortDescriptor",
    "ProcessEndpoint",
    "ProcessRpcAuditEntry",
    "ProcessRpcFailure",
    "ProcessRpcRequest",
    "ProcessRpcResponse",
    "ProcessRpcRoutes",
    "ProcessRpcTransport",
    "ProducerKind",
    "ProducerRef",
    "REFERENCE_EXAMPLE_SUITE",
    "RateMatchedSensor",
    "ReactiveSensorHandle",
    "ReactiveSensorSource",
    "ReadThenWriteNextEpochStep",
    "ReadablePort",
    "ReferenceExample",
    "Resistor",
    "RetentionSnapshot",
    "RetryLoop",
    "RetryPolicy",
    "RouteAuditSnapshot",
    "RouteIdentity",
    "RouteNamespace",
    "RoutePipeline",
    "RouteRef",
    "RouteRetentionPolicy",
    "RouteScope",
    "RuntimeRef",
    "ScheduleGuard",
    "ScheduledWriteSnapshot",
    "Schema",
    "SchemaRef",
    "SensorBackoffPolicy",
    "SensorDebugEnvelope",
    "SensorDebugStage",
    "SensorDebugTap",
    "SensorEvent",
    "SensorFrame",
    "SensorHealthHandle",
    "SensorHealthWatchdog",
    "SensorIdentity",
    "SensorLocation",
    "SensorRetryPolicy",
    "SensorSample",
    "SensorSourceHandle",
    "SensorTag",
    "SequenceCounter",
    "ShadowSnapshot",
    "Sink",
    "SnapshotStore",
    "SnapshotStoreRoutes",
    "Source",
    "StopToken",
    "StoreEntry",
    "StreamFamily",
    "StreamName",
    "StreamNode",
    "SystemClock",
    "TaintDomain",
    "TaintMark",
    "TaintRepair",
    "ThresholdFilter",
    "Timer",
    "TypedEnvelope",
    "TypedRoute",
    "Variant",
    "Watchdog",
    "WatermarkSnapshot",
    "WritablePort",
    "WriteBinding",
    "WriteBindings",
    "all_legos",
    "bridge_version",
    "dependencies_of",
    "dependency_closure_of",
    "dependents_of",
    "drain_frame_thread_queue",
    "get_lego",
    "health_status_schema",
    "implemented_reference_examples",
    "instrument_stream",
    "legos_by_layer",
    "legos_by_role",
    "logical_routes",
    "parse_sql_statement",
    "reference_example_suite",
    "route",
    "sensor_event_schema",
    "sensor_sample_schema",
    "shutdown",
    "sink",
    "source",
    "xor_checksum",
)
