"""Private Rx-compatible streaming facade for Manyfold internals.

Manyfold still builds on RxPy for its in-process Python stream surface. This
module keeps the re-export surface available to internal code without making it
part of the public ``manyfold`` namespace.
"""

from reactivex import (
    ConnectableObservable as ConnectableObservable,
    GroupedObservable as GroupedObservable,
    Notification as Notification,
    Observable as Observable,
    Observer as Observer,
    amb as amb,
    case as case,
    catch as catch,
    catch_with_iterable as catch_with_iterable,
    combine_latest as combine_latest,
    compose as compose,
    concat as concat,
    concat_with_iterable as concat_with_iterable,
    create as create,
    defer as defer,
    empty as empty,
    fork_join as fork_join,
    from_callable as from_callable,
    from_callback as from_callback,
    from_future as from_future,
    from_iterable as from_iterable,
    from_marbles as from_marbles,
    generate as generate,
    generate_with_relative_time as generate_with_relative_time,
    if_then as if_then,
    interval as interval,
    just as just,
    merge as merge,
    never as never,
    of as of,
    on_error_resume_next as on_error_resume_next,
    operators as operators,
    pipe as pipe,
    range as range,
    repeat_value as repeat_value,
    return_value as return_value,
    start as start,
    start_async as start_async,
    throw as throw,
    timer as timer,
    to_async as to_async,
    typing as typing,
    using as using,
    with_latest_from as with_latest_from,
    zip as zip,
)

from . import abc as abc
from .subject import Subject as Subject

__all__ = (
    "ConnectableObservable",
    "GroupedObservable",
    "Notification",
    "Observable",
    "Observer",
    "Subject",
    "abc",
    "amb",
    "case",
    "catch",
    "catch_with_iterable",
    "combine_latest",
    "compose",
    "concat",
    "concat_with_iterable",
    "create",
    "defer",
    "empty",
    "fork_join",
    "from_callable",
    "from_callback",
    "from_future",
    "from_iterable",
    "from_marbles",
    "generate",
    "generate_with_relative_time",
    "if_then",
    "interval",
    "just",
    "merge",
    "never",
    "of",
    "on_error_resume_next",
    "operators",
    "pipe",
    "range",
    "repeat_value",
    "return_value",
    "start",
    "start_async",
    "throw",
    "timer",
    "to_async",
    "typing",
    "using",
    "with_latest_from",
    "zip",
)
