# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "ClockDomainRef",
    "ClosedEnvelope",
    "ControlLoop",
    "CreditSnapshot",
    "Graph",
    "Layer",
    "LineageProfile",
    "Mailbox",
    "MailboxDescriptor",
    "NamespaceRef",
    "NoLineageMaterializerDropProfile",
    "OpenedEnvelope",
    "PayloadRef",
    "Plane",
    "PortDescriptor",
    "ProducerKind",
    "ProducerRef",
    "ReadablePort",
    "RetentionSnapshot",
    "RouteRef",
    "RuntimeRef",
    "ScheduleGuard",
    "SchemaRef",
    "TaintDomain",
    "TaintMark",
    "Variant",
    "WritablePort",
    "WriteBinding",
    "bridge_version",
]

@typing.final
class ClockDomainRef:
    @property
    def clock_domain_id(self) -> builtins.str: ...
    def __new__(cls, clock_domain_id: builtins.str) -> ClockDomainRef: ...

@typing.final
class ClosedEnvelope:
    @property
    def route(self) -> RouteRef: ...
    @property
    def producer(self) -> ProducerRef: ...
    @property
    def emitter(self) -> RuntimeRef: ...
    @property
    def seq_source(self) -> builtins.int: ...
    @property
    def control_epoch(self) -> typing.Optional[builtins.int]: ...
    @property
    def taints(self) -> builtins.list[TaintMark]: ...
    @property
    def guards(self) -> builtins.list[ScheduleGuard]: ...
    @property
    def payload_ref(self) -> PayloadRef: ...
    @property
    def payload_id(self) -> builtins.str: ...
    @property
    def has_inline_payload(self) -> builtins.bool: ...
    @property
    def inline_payload(self) -> builtins.bytes: ...
    def with_taints(self, taints: typing.Sequence[TaintMark]) -> ClosedEnvelope: ...
    def close(self) -> ClosedEnvelope: ...

@typing.final
class ControlLoop:
    @property
    def name(self) -> builtins.str: ...
    @property
    def epoch(self) -> builtins.int: ...
    def __new__(
        cls,
        name: builtins.str,
        read_routes: typing.Sequence[RouteRef],
        write_request: RouteRef,
    ) -> ControlLoop: ...

@typing.final
class CreditSnapshot:
    @property
    def route_display(self) -> builtins.str: ...
    @property
    def credit_class(self) -> builtins.str: ...
    @property
    def available(self) -> builtins.int: ...
    @property
    def blocked_senders(self) -> builtins.int: ...
    @property
    def dropped_messages(self) -> builtins.int: ...
    @property
    def largest_queue_depth(self) -> builtins.int: ...

@typing.final
class RetentionSnapshot:
    @property
    def route_display(self) -> builtins.str: ...
    @property
    def latest_seq_source(self) -> typing.Optional[builtins.int]: ...
    @property
    def metadata_event_count(self) -> builtins.int: ...
    @property
    def replay_count(self) -> builtins.int: ...
    @property
    def payload_count(self) -> builtins.int: ...
    @property
    def lineage_count(self) -> builtins.int: ...
    @property
    def trace_index_count(self) -> builtins.int: ...
    @property
    def causality_index_count(self) -> builtins.int: ...
    @property
    def correlation_index_count(self) -> builtins.int: ...
    @property
    def history_limit(self) -> typing.Optional[builtins.int]: ...

@typing.final
class LineageProfile: ...

@typing.final
class NoLineageMaterializerDropProfile: ...

@typing.final
class Graph:
    def __new__(cls) -> Graph: ...
    def register_port(self, route: RouteRef) -> RouteRef: ...
    def compile_lineage_profile(
        self, trace_id: builtins.str, causality_id: builtins.str
    ) -> LineageProfile: ...
    def release_lineage_profile(self, profile: LineageProfile) -> None: ...
    def compile_no_lineage_materializer_drop_profile(
        self, route: RouteRef, target_route: RouteRef
    ) -> NoLineageMaterializerDropProfile: ...
    def release_no_lineage_materializer_drop_profile(
        self, profile: NoLineageMaterializerDropProfile
    ) -> None: ...
    def emit_no_lineage_materializer_drop_profile_python(
        self,
        profile: NoLineageMaterializerDropProfile,
        payload: typing.Sequence[builtins.int],
    ) -> builtins.bool: ...
    def attach_noop_correlation_store(self) -> None: ...
    def attach_noop_lineage_store(self) -> None: ...
    def attach_retained_correlation_store(self) -> None: ...
    def attach_retained_lineage_store(self) -> None: ...
    def configure_retention(
        self,
        route: RouteRef,
        latest_replay_policy: builtins.str,
        durability_class: builtins.str,
        replay_window: builtins.str,
        payload_retention_policy: builtins.str,
        history_limit: typing.Optional[builtins.int] = None,
        lineage_retention_policy: typing.Optional[builtins.str] = None,
    ) -> None: ...
    def read(self, route: RouteRef) -> ReadablePort: ...
    def writable_port(self, route: RouteRef) -> WritablePort: ...
    def emit(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
    ) -> builtins.list[ClosedEnvelope]: ...
    def emit_single_if_unrouted(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
    ) -> typing.Optional[ClosedEnvelope]: ...
    def emit_single_if_unrouted_drop(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_and_materializer_drop(
        self,
        route: RouteRef,
        target_route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_and_materializer_drop_python(
        self,
        route: RouteRef,
        target_route: RouteRef,
        payload: typing.Sequence[builtins.int],
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_with_lineage_no_parents(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
        trace_id: typing.Optional[builtins.str] = None,
        causality_id: typing.Optional[builtins.str] = None,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> typing.Optional[ClosedEnvelope]: ...
    def emit_single_if_unrouted_with_lineage_no_parents_and_materializers(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
        trace_id: typing.Optional[builtins.str] = None,
        causality_id: typing.Optional[builtins.str] = None,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> typing.Optional[builtins.list[ClosedEnvelope]]: ...
    def emit_single_if_unrouted_with_lineage_no_parents_and_materializers_drop(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
        trace_id: typing.Optional[builtins.str] = None,
        causality_id: typing.Optional[builtins.str] = None,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_with_lineage_no_parents_and_materializers_drop_python(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        trace_id: typing.Optional[builtins.str] = None,
        causality_id: typing.Optional[builtins.str] = None,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_with_lineage_ids_no_parents_and_materializers_drop_python(
        self,
        route: RouteRef,
        payload: typing.Sequence[builtins.int],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_with_lineage_ids_no_parents_and_materializer_drop_python(
        self,
        route: RouteRef,
        target_route: RouteRef,
        payload: typing.Sequence[builtins.int],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.bool: ...
    def emit_single_if_unrouted_with_lineage_profile_no_parents_and_materializer_drop_python(
        self,
        route: RouteRef,
        target_route: RouteRef,
        payload: typing.Sequence[builtins.int],
        profile: LineageProfile,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.bool: ...
    def materialize_bytes_one_parent(
        self,
        source_route: RouteRef,
        source_seq_source: builtins.int,
        target_route: RouteRef,
        producer: typing.Optional[ProducerRef] = None,
    ) -> typing.Optional[ClosedEnvelope]: ...
    def register_materialize_bytes(
        self, source_route: RouteRef, target_route: RouteRef
    ) -> builtins.bool: ...
    def unregister_materialize_bytes(
        self, source_route: RouteRef, target_route: RouteRef
    ) -> builtins.bool: ...
    def register_binding(
        self, name: builtins.str, binding: WriteBinding
    ) -> WriteBinding: ...
    def mailbox(
        self, name: builtins.str, descriptor: typing.Optional[MailboxDescriptor] = None
    ) -> Mailbox: ...
    def connect(self, source: typing.Any, sink: typing.Any) -> bool: ...
    def disconnect(self, source: typing.Any, sink: typing.Any) -> builtins.bool: ...
    def install(self, loop_ref: ControlLoop) -> None: ...
    def tick_control_loop(self, name: builtins.str) -> ClosedEnvelope: ...
    def catalog(self) -> builtins.list[RouteRef]: ...
    def describe_route(self, route: RouteRef) -> PortDescriptor: ...
    def latest(self, route: RouteRef) -> typing.Optional[ClosedEnvelope]: ...
    def replay(self, route: RouteRef) -> builtins.list[ClosedEnvelope]: ...
    def record_lineage(
        self,
        route_display: builtins.str,
        seq_source: builtins.int,
        producer_id: typing.Optional[builtins.str],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str],
        parent_events: typing.Sequence[tuple[builtins.str, builtins.int]],
    ) -> None: ...
    def record_lineage_for_route(
        self,
        route: RouteRef,
        seq_source: builtins.int,
        producer_id: typing.Optional[builtins.str],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str],
        parent_events: typing.Sequence[tuple[builtins.str, builtins.int]],
    ) -> None: ...
    def record_lineage_for_route_no_parents(
        self,
        route: RouteRef,
        seq_source: builtins.int,
        producer_id: typing.Optional[builtins.str],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str],
    ) -> None: ...
    def record_lineage_for_route_one_parent(
        self,
        route: RouteRef,
        seq_source: builtins.int,
        producer_id: typing.Optional[builtins.str],
        trace_id: builtins.str,
        causality_id: builtins.str,
        correlation_id: typing.Optional[builtins.str],
        parent_route_display: builtins.str,
        parent_seq_source: builtins.int,
    ) -> None: ...
    def lineage_records(
        self,
        route: typing.Optional[RouteRef] = None,
        trace_id: typing.Optional[builtins.str] = None,
        causality_id: typing.Optional[builtins.str] = None,
        correlation_id: typing.Optional[builtins.str] = None,
    ) -> builtins.list[
        tuple[
            builtins.str,
            builtins.int,
            typing.Optional[builtins.str],
            builtins.str,
            builtins.str,
            typing.Optional[builtins.str],
            builtins.list[tuple[builtins.str, builtins.int]],
        ]
    ]: ...
    def lineage_record_for_route_event(
        self, route: RouteRef, seq_source: builtins.int
    ) -> typing.Optional[
        tuple[
            builtins.str,
            builtins.int,
            typing.Optional[builtins.str],
            builtins.str,
            builtins.str,
            typing.Optional[builtins.str],
            builtins.list[tuple[builtins.str, builtins.int]],
        ]
    ]: ...
    def retained_payload_count(self, route: RouteRef) -> builtins.int: ...
    def payload_by_id(
        self, payload_id: builtins.str
    ) -> typing.Optional[builtins.bytes]: ...
    def retention_snapshot(
        self, route: typing.Optional[RouteRef] = None
    ) -> builtins.list[RetentionSnapshot]: ...
    def retention_violations(self) -> builtins.list[builtins.str]: ...
    def lineage_intern_value_count(self) -> builtins.int: ...
    def topology(self) -> builtins.list[tuple[builtins.str, builtins.str]]: ...
    def validate_graph(self) -> builtins.list[builtins.str]: ...
    def credit_snapshot(self) -> builtins.list[CreditSnapshot]: ...

@typing.final
class Layer:
    Raw: Layer
    Logical: Layer
    Shadow: Layer
    Bulk: Layer
    Internal: Layer
    Ephemeral: Layer
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Mailbox:
    @property
    def ingress(self) -> WritablePort: ...
    @property
    def egress(self) -> ReadablePort: ...
    def name(self) -> builtins.str: ...
    def depth(self) -> builtins.int: ...
    def available_credit(self) -> builtins.int: ...
    def blocked_writes(self) -> builtins.int: ...
    def dropped_messages(self) -> builtins.int: ...
    def coalesced_messages(self) -> builtins.int: ...
    def delivered_messages(self) -> builtins.int: ...

@typing.final
class MailboxDescriptor:
    @property
    def capacity(self) -> builtins.int: ...
    @property
    def delivery_mode(self) -> builtins.str: ...
    @property
    def ordering_policy(self) -> builtins.str: ...
    @property
    def overflow_policy(self) -> builtins.str: ...
    def __new__(
        cls,
        capacity: builtins.int = 128,
        delivery_mode: builtins.str = "mpsc_serial",
        ordering_policy: builtins.str = "fifo",
        overflow_policy: builtins.str = "block",
    ) -> MailboxDescriptor: ...

@typing.final
class NamespaceRef:
    @property
    def plane(self) -> Plane: ...
    @property
    def layer(self) -> Layer: ...
    @property
    def owner(self) -> builtins.str: ...
    def __new__(
        cls, plane: Plane, layer: Layer, owner: builtins.str
    ) -> NamespaceRef: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OpenedEnvelope:
    @property
    def closed(self) -> ClosedEnvelope: ...
    @property
    def payload(self) -> builtins.list[builtins.int]: ...
    def close(self) -> ClosedEnvelope: ...

@typing.final
class PayloadRef:
    @property
    def payload_id(self) -> builtins.str: ...
    @property
    def logical_length_bytes(self) -> builtins.int: ...
    @property
    def codec_id(self) -> builtins.str: ...
    @property
    def inline_bytes(self) -> builtins.list[builtins.int]: ...
    def __new__(
        cls,
        payload_id: builtins.str,
        logical_length_bytes: builtins.int = 0,
        codec_id: builtins.str = "identity",
        inline_bytes: typing.Sequence[builtins.int] = b"",
    ) -> PayloadRef: ...

@typing.final
class Plane:
    Read: Plane
    Write: Plane
    State: Plane
    Query: Plane
    Debug: Plane
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PortDescriptor:
    @property
    def route_display(self) -> builtins.str: ...
    @property
    def human_description(self) -> builtins.str: ...
    @property
    def payload_open_policy(self) -> builtins.str: ...
    @property
    def backpressure_policy(self) -> builtins.str: ...
    @property
    def debug_enabled(self) -> builtins.bool: ...

@typing.final
class ProducerKind:
    Device: ProducerKind
    FirmwareAgent: ProducerKind
    Transform: ProducerKind
    ControlLoop: ProducerKind
    Mailbox: ProducerKind
    QueryService: ProducerKind
    Application: ProducerKind
    Bridge: ProducerKind
    Reconciler: ProducerKind
    LifecycleService: ProducerKind
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProducerRef:
    @property
    def producer_id(self) -> builtins.str: ...
    @property
    def kind(self) -> ProducerKind: ...
    def __new__(cls, producer_id: builtins.str, kind: ProducerKind) -> ProducerRef: ...

@typing.final
class ReadablePort:
    def meta(self) -> builtins.list[ClosedEnvelope]: ...
    def open(self) -> builtins.list[OpenedEnvelope]: ...
    def latest(self) -> typing.Optional[ClosedEnvelope]: ...
    def describe(self) -> PortDescriptor: ...

@typing.final
class RouteRef:
    @property
    def namespace(self) -> NamespaceRef: ...
    @property
    def family(self) -> builtins.str: ...
    @property
    def stream(self) -> builtins.str: ...
    @property
    def variant(self) -> Variant: ...
    @property
    def schema(self) -> SchemaRef: ...
    def __new__(
        cls,
        namespace: NamespaceRef,
        family: builtins.str,
        stream: builtins.str,
        variant: Variant,
        schema: SchemaRef,
    ) -> RouteRef: ...
    def display(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RuntimeRef:
    @property
    def runtime_id(self) -> builtins.str: ...
    def __new__(cls, runtime_id: builtins.str) -> RuntimeRef: ...

@typing.final
class ScheduleGuard:
    @property
    def expires_at_epoch(self) -> typing.Optional[builtins.int]: ...
    @staticmethod
    def not_before_epoch(epoch: builtins.int) -> ScheduleGuard: ...
    @staticmethod
    def wait_for_ack(route: RouteRef) -> ScheduleGuard: ...

@typing.final
class SchemaRef:
    @property
    def schema_id(self) -> builtins.str: ...
    @property
    def version(self) -> builtins.int: ...
    def __new__(cls, schema_id: builtins.str, version: builtins.int) -> SchemaRef: ...

@typing.final
class TaintDomain:
    Time: TaintDomain
    Order: TaintDomain
    Delivery: TaintDomain
    Determinism: TaintDomain
    Scheduling: TaintDomain
    Trust: TaintDomain
    Coherence: TaintDomain
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...

@typing.final
class TaintMark:
    @property
    def domain(self) -> TaintDomain: ...
    @property
    def value_id(self) -> builtins.str: ...
    @property
    def origin_id(self) -> builtins.str: ...
    def __new__(
        cls, domain: TaintDomain, value_id: builtins.str, origin_id: builtins.str
    ) -> TaintMark: ...

@typing.final
class Variant:
    Meta: Variant
    Payload: Variant
    Request: Variant
    Desired: Variant
    Reported: Variant
    Effective: Variant
    Ack: Variant
    State: Variant
    QueryRequest: Variant
    QueryResponse: Variant
    Event: Variant
    Health: Variant
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class WritablePort:
    def write(
        self,
        payload: typing.Sequence[builtins.int],
        producer: typing.Optional[ProducerRef] = None,
        control_epoch: typing.Optional[builtins.int] = None,
    ) -> ClosedEnvelope: ...
    def describe(self) -> PortDescriptor: ...

@typing.final
class WriteBinding:
    @property
    def request(self) -> RouteRef: ...
    @property
    def desired(self) -> RouteRef: ...
    @property
    def reported(self) -> RouteRef: ...
    @property
    def effective(self) -> RouteRef: ...
    @property
    def ack(self) -> typing.Optional[RouteRef]: ...
    def __new__(
        cls,
        request: RouteRef,
        desired: RouteRef,
        reported: RouteRef,
        effective: RouteRef,
        ack: typing.Optional[RouteRef] = None,
    ) -> WriteBinding: ...

def bridge_version() -> builtins.str: ...
